version: '2'

services:
  app:
    image: 'test-java-app:latest'
    container_name: test-java-app
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/cinematics?currentSchema=public&user=testcomposeuser&password=Test@123
      - SPRING_DATASOURCE_USERNAME=testcomposeuser
      - SPRING_DATASOURCE_PASSWORD=Test@123
    depends_on:
      - postgresdb

  postgresdb:
    image: 'postgres:14.6'
    container_name: postgresdb
    volumes:
      - ./initializeDB.sql:/docker-entrypoint-initdb.d/createstuff.sql
    environment:
      - POSTGRES_USER=testcomposeuser
      - POSTGRES_PASSWORD=Test@123
      - POSTGRES_DB=cinematics
